/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ProtectedRouteImport } from "./routes/_protected"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as ProtectedCardPaymentsRouteImport } from "./routes/_protected/card-payments"
import { Route as ProtectedDashboardRouteImport } from "./routes/_protected/dashboard"
import { Route as ProtectedRequestsRouteImport } from "./routes/_protected/requests"
import { Route as ProtectedServicesRouteImport } from "./routes/_protected/services"
import { Route as ProtectedSettingsRouteImport } from "./routes/_protected/settings"
import { Route as ProtectedUsersRouteImport } from "./routes/_protected/users"
import { Route as ProtectedUsersIndexRouteImport } from "./routes/_protected/users/index"
import { Route as ProtectedUsersAdminsRouteImport } from "./routes/_protected/users/admins"
import { Route as ProtectedUsersCustomersRouteImport } from "./routes/_protected/users/customers"
import { Route as ProtectedUsersProfessionalsRouteImport } from "./routes/_protected/users/professionals"
import { Route as ProtectedUsersStaffRouteImport } from "./routes/_protected/users/staff"
import { Route as ProtectedUsersSuperAdminsRouteImport } from "./routes/_protected/users/super-admins"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: "/_protected",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedCardPaymentsRoute = ProtectedCardPaymentsRouteImport.update({
  id: "/card-payments",
  path: "/card-payments",
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRequestsRoute = ProtectedRequestsRouteImport.update({
  id: "/requests",
  path: "/requests",
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedServicesRoute = ProtectedServicesRouteImport.update({
  id: "/services",
  path: "/services",
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUsersRoute = ProtectedUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUsersIndexRoute = ProtectedUsersIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ProtectedUsersRoute,
} as any)
const ProtectedUsersAdminsRoute = ProtectedUsersAdminsRouteImport.update({
  id: "/admins",
  path: "/admins",
  getParentRoute: () => ProtectedUsersRoute,
} as any)
const ProtectedUsersCustomersRoute = ProtectedUsersCustomersRouteImport.update({
  id: "/customers",
  path: "/customers",
  getParentRoute: () => ProtectedUsersRoute,
} as any)
const ProtectedUsersProfessionalsRoute =
  ProtectedUsersProfessionalsRouteImport.update({
    id: "/professionals",
    path: "/professionals",
    getParentRoute: () => ProtectedUsersRoute,
  } as any)
const ProtectedUsersStaffRoute = ProtectedUsersStaffRouteImport.update({
  id: "/staff",
  path: "/staff",
  getParentRoute: () => ProtectedUsersRoute,
} as any)
const ProtectedUsersSuperAdminsRoute =
  ProtectedUsersSuperAdminsRouteImport.update({
    id: "/super-admins",
    path: "/super-admins",
    getParentRoute: () => ProtectedUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/card-payments": typeof ProtectedCardPaymentsRoute
  "/dashboard": typeof ProtectedDashboardRoute
  "/requests": typeof ProtectedRequestsRoute
  "/services": typeof ProtectedServicesRoute
  "/settings": typeof ProtectedSettingsRoute
  "/users": typeof ProtectedUsersRouteWithChildren
  "/users/admins": typeof ProtectedUsersAdminsRoute
  "/users/customers": typeof ProtectedUsersCustomersRoute
  "/users/professionals": typeof ProtectedUsersProfessionalsRoute
  "/users/staff": typeof ProtectedUsersStaffRoute
  "/users/super-admins": typeof ProtectedUsersSuperAdminsRoute
  "/users/": typeof ProtectedUsersIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/card-payments": typeof ProtectedCardPaymentsRoute
  "/dashboard": typeof ProtectedDashboardRoute
  "/requests": typeof ProtectedRequestsRoute
  "/services": typeof ProtectedServicesRoute
  "/settings": typeof ProtectedSettingsRoute
  "/users/admins": typeof ProtectedUsersAdminsRoute
  "/users/customers": typeof ProtectedUsersCustomersRoute
  "/users/professionals": typeof ProtectedUsersProfessionalsRoute
  "/users/staff": typeof ProtectedUsersStaffRoute
  "/users/super-admins": typeof ProtectedUsersSuperAdminsRoute
  "/users": typeof ProtectedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_protected": typeof ProtectedRouteWithChildren
  "/login": typeof LoginRoute
  "/_protected/card-payments": typeof ProtectedCardPaymentsRoute
  "/_protected/dashboard": typeof ProtectedDashboardRoute
  "/_protected/requests": typeof ProtectedRequestsRoute
  "/_protected/services": typeof ProtectedServicesRoute
  "/_protected/settings": typeof ProtectedSettingsRoute
  "/_protected/users": typeof ProtectedUsersRouteWithChildren
  "/_protected/users/admins": typeof ProtectedUsersAdminsRoute
  "/_protected/users/customers": typeof ProtectedUsersCustomersRoute
  "/_protected/users/professionals": typeof ProtectedUsersProfessionalsRoute
  "/_protected/users/staff": typeof ProtectedUsersStaffRoute
  "/_protected/users/super-admins": typeof ProtectedUsersSuperAdminsRoute
  "/_protected/users/": typeof ProtectedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/card-payments"
    | "/dashboard"
    | "/requests"
    | "/services"
    | "/settings"
    | "/users"
    | "/users/admins"
    | "/users/customers"
    | "/users/professionals"
    | "/users/staff"
    | "/users/super-admins"
    | "/users/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/card-payments"
    | "/dashboard"
    | "/requests"
    | "/services"
    | "/settings"
    | "/users/admins"
    | "/users/customers"
    | "/users/professionals"
    | "/users/staff"
    | "/users/super-admins"
    | "/users"
  id:
    | "__root__"
    | "/"
    | "/_protected"
    | "/login"
    | "/_protected/card-payments"
    | "/_protected/dashboard"
    | "/_protected/requests"
    | "/_protected/services"
    | "/_protected/settings"
    | "/_protected/users"
    | "/_protected/users/admins"
    | "/_protected/users/customers"
    | "/_protected/users/professionals"
    | "/_protected/users/staff"
    | "/_protected/users/super-admins"
    | "/_protected/users/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_protected": {
      id: "/_protected"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_protected/card-payments": {
      id: "/_protected/card-payments"
      path: "/card-payments"
      fullPath: "/card-payments"
      preLoaderRoute: typeof ProtectedCardPaymentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    "/_protected/dashboard": {
      id: "/_protected/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    "/_protected/requests": {
      id: "/_protected/requests"
      path: "/requests"
      fullPath: "/requests"
      preLoaderRoute: typeof ProtectedRequestsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    "/_protected/services": {
      id: "/_protected/services"
      path: "/services"
      fullPath: "/services"
      preLoaderRoute: typeof ProtectedServicesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    "/_protected/settings": {
      id: "/_protected/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    "/_protected/users": {
      id: "/_protected/users"
      path: "/users"
      fullPath: "/users"
      preLoaderRoute: typeof ProtectedUsersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    "/_protected/users/": {
      id: "/_protected/users/"
      path: "/"
      fullPath: "/users/"
      preLoaderRoute: typeof ProtectedUsersIndexRouteImport
      parentRoute: typeof ProtectedUsersRoute
    }
    "/_protected/users/admins": {
      id: "/_protected/users/admins"
      path: "/admins"
      fullPath: "/users/admins"
      preLoaderRoute: typeof ProtectedUsersAdminsRouteImport
      parentRoute: typeof ProtectedUsersRoute
    }
    "/_protected/users/customers": {
      id: "/_protected/users/customers"
      path: "/customers"
      fullPath: "/users/customers"
      preLoaderRoute: typeof ProtectedUsersCustomersRouteImport
      parentRoute: typeof ProtectedUsersRoute
    }
    "/_protected/users/professionals": {
      id: "/_protected/users/professionals"
      path: "/professionals"
      fullPath: "/users/professionals"
      preLoaderRoute: typeof ProtectedUsersProfessionalsRouteImport
      parentRoute: typeof ProtectedUsersRoute
    }
    "/_protected/users/staff": {
      id: "/_protected/users/staff"
      path: "/staff"
      fullPath: "/users/staff"
      preLoaderRoute: typeof ProtectedUsersStaffRouteImport
      parentRoute: typeof ProtectedUsersRoute
    }
    "/_protected/users/super-admins": {
      id: "/_protected/users/super-admins"
      path: "/super-admins"
      fullPath: "/users/super-admins"
      preLoaderRoute: typeof ProtectedUsersSuperAdminsRouteImport
      parentRoute: typeof ProtectedUsersRoute
    }
  }
}

interface ProtectedUsersRouteChildren {
  ProtectedUsersAdminsRoute: typeof ProtectedUsersAdminsRoute
  ProtectedUsersCustomersRoute: typeof ProtectedUsersCustomersRoute
  ProtectedUsersProfessionalsRoute: typeof ProtectedUsersProfessionalsRoute
  ProtectedUsersStaffRoute: typeof ProtectedUsersStaffRoute
  ProtectedUsersSuperAdminsRoute: typeof ProtectedUsersSuperAdminsRoute
  ProtectedUsersIndexRoute: typeof ProtectedUsersIndexRoute
}

const ProtectedUsersRouteChildren: ProtectedUsersRouteChildren = {
  ProtectedUsersAdminsRoute: ProtectedUsersAdminsRoute,
  ProtectedUsersCustomersRoute: ProtectedUsersCustomersRoute,
  ProtectedUsersProfessionalsRoute: ProtectedUsersProfessionalsRoute,
  ProtectedUsersStaffRoute: ProtectedUsersStaffRoute,
  ProtectedUsersSuperAdminsRoute: ProtectedUsersSuperAdminsRoute,
  ProtectedUsersIndexRoute: ProtectedUsersIndexRoute,
}

const ProtectedUsersRouteWithChildren = ProtectedUsersRoute._addFileChildren(
  ProtectedUsersRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedCardPaymentsRoute: typeof ProtectedCardPaymentsRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedRequestsRoute: typeof ProtectedRequestsRoute
  ProtectedServicesRoute: typeof ProtectedServicesRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedUsersRoute: typeof ProtectedUsersRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedCardPaymentsRoute: ProtectedCardPaymentsRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedRequestsRoute: ProtectedRequestsRoute,
  ProtectedServicesRoute: ProtectedServicesRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedUsersRoute: ProtectedUsersRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
